// Single source of truth for works, exhibitions and shared site data.

const projectList = [
  {
    slug: "UnlitHouse",
    number: "01",
    year: "2026",
    title: "Within the Unlit House",
    medium: "Multi-channel video and sound installation, mixed media Dimensions Varis",
    duration: "video: 28'37\"",
    hero: "/pro/work-new/Within the Unlit House/01.png",
    heroPosition: "center bottom",
    href: "/workpage/UnlitHouse",
    gallery: [
      "/pro/work-new/Within the Unlit House/01.png",
      "/pro/work-new/Within the Unlit House/02.png",
      "/pro/work-new/Within the Unlit House/03.png",
      "/pro/work-new/Within the Unlit House/04.png",
      "/pro/work-new/Within the Unlit House/05.png",
      "/pro/work-new/Within the Unlit House/06.png",
      "/pro/work-new/Within the Unlit House/07.png",
      "/pro/work-new/Within the Unlit House/08.png",
      "/pro/work-new/Within the Unlit House/09.png",
      "/pro/work-new/Within the Unlit House/10.png",
      "/pro/work-new/Within the Unlit House/11.png",
    ],
    statement: [
      "Within the Unlit House explores invisibility, resistance, and the shifting boundaries through which an ?us? is constituted within minority contexts. Rather than focusing on origins or formal studies of tradition, the project addresses how visibility and invisibility operate as lived conditions between collectives and toward the outside world.",
    ],
    imageCredit: [
      "圖片出處",
      "展場圖片／C-LAB提供",
      "攝影／嘟嚕影像工作室",
      "Image credit",
      "Exhibition photos / Courtesy of C-LAB",
      "Photography / dulub studio",
    ],
    creditImages: [
      "/pro/work-new/Within the Unlit House/01.png",
      "/pro/work-new/Within the Unlit House/07.png",
      "/pro/work-new/Within the Unlit House/08.png",
      "/pro/work-new/Within the Unlit House/09.png",
      "/pro/work-new/Within the Unlit House/10.png",
      "/pro/work-new/Within the Unlit House/11.png",
    ],
  },
  {
    slug: "FriendFromAfar",
    number: "02",
    year: "2025",
    title: "Misafafahiyan - Teman dari Jauh",
    medium: "Single-channel video, mixed media Dimensions Varis",
    duration: "42'22\"",
    hero: "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/01.png",
    href: "/workpage/FriendFromAfar",
    gallery: [
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/01.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/02.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/03.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/04.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/05.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/06.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/07.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/08.png",
      "/pro/work-new/Misafafahiyan - Teman dari Jauh (Misafafahiyan - Friend from Afar)/09.png",
    ],
    statement: [
      "This work is an extension of the artist?s project Misafafahiyan Metamorphosis in Yogyakarta. It brings together local transgender performers?Mami Tata, Ibu Sinta, and Siska?with Haohao, an Amis transgender performer from Taiwan. Using karaoke backing tracks as a shared medium, they exchange personal stories and emotions. These encounters unfold not only through singing and performance but also across popular music, beauty salons, and the textures of daily life, reflecting how each shapes and enacts her own sense of space.",
      "As a major cultural and performance hub in Indonesia, Yogyakarta has long nurtured both the visibility and the diverse expressions of its transgender communities, producing a cultural landscape that is at once marginal and vibrantly alive. Through these translocal connections, the work gathers self-narratives and moments of resonance, illuminating the resilience and artistry that sustain transgender lives on the streets. At the same time, it opens a space for rethinking difference, recognition, and coexistence across cultures.",
    ],
  },
  {
    slug: "WhiteDeer",
    number: "03",
    year: "2025",
    title: "There is a white deer in the mountain",
    medium: "Duo-channel video",
    duration: "12'00\"",
    hero: "/pro/work-new/There is a white deer in the mountain (山裡有隻白色的鹿)/01.png",
    href: "/workpage/WhiteDeer",
    gallery: [
      "/pro/work-new/There is a white deer in the mountain (山裡有隻白色的鹿)/01.png",
      "/pro/work-new/There is a white deer in the mountain (山裡有隻白色的鹿)/02.png",
      "/pro/work-new/There is a white deer in the mountain (山裡有隻白色的鹿)/03.png",
      "/pro/work-new/There is a white deer in the mountain (山裡有隻白色的鹿)/04.png",
    ],
    statement: [
      "The deer herder says that deer who are given names become difficult to raise, so most of the deer in his enclosure don't have names. However, even without names, he still feels he often sees their blurry silhouettes in the mountains after nightfall?",
      "There?s a White Deer in the Mountains takes as its starting point the folk legends of sika deer, fictional stories tanned with oral memories and archival documents, exploring the dialectic and imagination between circular time, overlapping regimes, memory, and islands.",
    ],
  },
  {
    slug: "Lakec",
    number: "01",
    year: "2018",
    title: "Lakec",
    medium: "Moving image",
    duration: "20'34\"",
    hero: "/pro/work-new/Lakec/Lakec＿1.png",
    href: "/workpage/Lakec",
    gallery: [
      "/pro/work-new/Lakec/Lakec＿1.png",
      "/pro/work-new/Lakec/Lakec＿2.png",
      "/pro/work-new/Lakec/Lakec＿3.png",
      "/pro/work-new/Lakec/Lakec＿4.png",
      "/pro/work-new/Lakec/Lakec＿5.png",
      "/pro/work-new/Lakec/Lakec＿6.png",
      "/pro/work-new/Lakec/Lakec＿7.png",
      "/pro/work-new/Lakec/Lakec＿8.png",
      "/pro/work-new/Lakec/Lakec＿9.png",
    ],
    statement: [
      "Lakec is the inspiration from the memory of Posak's childhood memories of the Amis people who live by the water, and her younger brother who comes to work in Taipei from her hometown. It traces the experience of many indigenous young people and even the previous generation who leave home and try to survive in the city. Further, Posak connects Satefo (Fata'an river) from her hometown and the Xiu Bitan that is next to the Xindian River with the image of flowing. Through interviews, oral storytelling, myths and songs delivered by the tribal people of the two places, it depicts a picture of the formable space and life between migratory nomadism and the river journey home.",
    ],
  },
  {
    slug: "Simpleriver",
    number: "02",
    year: "2020",
    title: "Lakec: A Very Simple River",
    medium: "Moving image",
    duration: "14'32\"",
    hero: "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿1.png",
    href: "/workpage/Simpleriver",
    gallery: [
      "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿1.png",
      "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿2.png",
      "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿3.png",
      "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿4.png",
      "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿5.png",
      "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿6.png",
      "/pro/work-new/Lakec_ A Very Simple River/A very simple river＿7.png",
    ],
    statement: [
      "Posak Jodian?s first work about the Malay Peninsula. Through the \"writing\" of the lens to capture the essence of the river. This work, a journey into the heart of Malaysia's indigenous communities, focuses on the Jakun people of the Peninsula. Drawing from their oral stories and lived experiences, Posak intricately weaves a narrative that interplay between the documented and the undocumented within the collective memory of the Jakun community. A landscape existing in the subtle realm between tangible and intangible geographies.",
    ],
  },
  {
    slug: "Misafafahiyan",
    number: "03",
    year: "2022",
    title: "Misafafahiyan Metamorphosis",
    medium: "Moving image",
    duration: "16'17\"",
    hero: "/pro/work-new/Misafafahiyan Metamorphosis/01.png",
    href: "/workpage/Misafafahiyan",
    gallery: [
      "/pro/work-new/Misafafahiyan Metamorphosis/01.png",
      "/pro/work-new/Misafafahiyan Metamorphosis/02.png",
      "/pro/work-new/Misafafahiyan Metamorphosis/03.png",
      "/pro/work-new/Misafafahiyan Metamorphosis/04.png",
      "/pro/work-new/Misafafahiyan Metamorphosis/05.png",
      "/pro/work-new/Misafafahiyan Metamorphosis/06.png",
      "/pro/work-new/Misafafahiyan Metamorphosis/07.jpeg",
      "/pro/work-new/Misafafahiyan Metamorphosis/08.jpeg",
      "/pro/work-new/Misafafahiyan Metamorphosis/09.jpeg",
      "/pro/work-new/Misafafahiyan Metamorphosis/10.jpg",
      "/pro/work-new/Misafafahiyan Metamorphosis/11.jpg",
    ],
    statement: [
      "Misafafahiyan Metamorphosis focuses on Hao Hao, a 70-years-old Amis trans performer living in Fata?an, an Amis tribe of Taiwan's indigenous peoples. The work includes a 16-minutes video and three photo printing puzzles. In the popular style of karaoke backing tracks, the music and sounds of Hao Hao's daily life are interwoven through directing, dialogue, dress up, and self-mockery. The themes of the songs in the video range from depicting familial love, emotions upon returning to hometown, and the portrayal of nightlife. Hao Hao, attempting to bring the moving and labor experiences of Taiwan's indigenous people and the displaced urban indigenous people's bodies hidden in the last century into the contemporary art field through visual development. This creates an increasingly complex \"historical image\" of indigenous peoples, portraying a survival technique of \"self-assembly\" and a counter-attack path of gender differentiation.",
    ],
  },
];

export const projects = projectList
  .slice()
  .sort((a, b) => Number(b.year) - Number(a.year))
  .map((project, index) => ({
    ...project,
    hero: project.gallery?.[0] || project.hero,
    number: String(index + 1).padStart(2, "0"),
  }));

export const portrait = "/pro/posak.webp";

export const exhibitions = [
  ["2008", "Self-portrait showed at Hualien Creative and Cultural Industries Park."],
  ["2011", "Story of Bai published on Taiwan Indigenous TV (TITV)."],
  ["2012", "Naruwan—Life Finds a Way—Taiwan Indigenous Artists Exhibition."],
  ["2018", "Lakec showed at Open Contemporary Art Center’s (OCAC) “PETAMU Project”."],
  ["2018", "Lakec showed at A+ WORKS of ART “A+ Online Festival of Video Art”."],
  ["2019", "Bitter Sweet participated in Open Contemporary Art Center’s project, showed at Taiwan Museum of Fine Arts."],
  ["2019", "Asian Art Biennial: The Strangers from beyond the Mountain and the Sea."],
  ["2019", "Palm Trees, Helicopters, the Boulder, and the Storyteller included in Nusantara Archive, published on the No Man’s Land online platform."],
  ["2020", "Lakec: A Very Simple River participated in Nusantara Archive and showed at Taipei Fine Arts Museum “The Secret South”."],
  ["2021", "Lakec project published in ACT 85: Indigenous Fields, Contemporary Transformations—Indigeneity in Arts and Confusions in Plurality, in the “Remapping—Paper Exhibition”."],
  ["2021", "Lakec project published on Pulima Link “Remapping”."],
  ["2021", "Lakec project received an Excellent Work Award in the Pulima Art Award."],
  ["2021", "Lakec: A Very Simple River showed at Hong-gah Museum “The Oceans and the Interpreters—Interpreters’ Screening II: The Mysterious Island”."],
  ["2022", "Lakec: A Very Simple River showed at Taitung Art Museum “Another Continent”."],
  ["2022", "Misafafahiyan Metamorphosis showed at Solid Art “Ocean and Interpreters”."],
  ["2023", "Misafafahiyan Metamorphosis showed at Britto Arts Trust “Ocean and Interpreters” in Dhaka, Bangladesh."],
  ["2023", "Misafafahiyan Metamorphosis received a Jury Award in the Pulima Art Award."],
  ["2023", "Misafafahiyan Metamorphosis showed at Jogja Fotografis Festival “Frame” in Yogyakarta, Indonesia."],
  ["2023", "Misafafahiyan Metamorphosis showed at Hualien Creative and Cultural Industries Park."],
  ["2023", "Pulima Art Festival “Amorous Mountains, Erotic Seas: Queer, Indigene, and the Hidden History”."],
  ["2025", "Participated in Biennale Jogja 18 “KAWRUH: Land of Rooted Practices,” Yogyakarta, Indonesia, 5 October–20 November 2025."],
  ["2026", "WE Are Becoming, presenting In the House Where Light Is Almost Invisible, at Taiwan Contemporary Culture Lab (C-LAB), Taipei, Taiwan, 8 May–16 August 2026."],
  ["2026", "Horizon Ablaze: Culture and Contemporary Art of Heat, at Taichung Museum of Art, Taichung, Taiwan, 15 May–30 August 2026."],
].sort((a, b) => Number(b[0]) - Number(a[0]));

export const newsItems = [
  {
    year: "2026",
    dates: "08 May — 16 August 2026",
    title: "WE Are Becoming",
    location: "Taiwan Contemporary Culture Lab (C-LAB), Taipei, Taiwan",
    visual: "we-are-becoming",
    href: "https://clab.org.tw/en/events/we-are-becoming/",
  },
  {
    year: "2026",
    dates: "15 May — 30 August 2026",
    title: "Horizon Ablaze: Culture and Contemporary Art of Heat",
    location: "Taichung Museum of Art, Taichung, Taiwan",
    image: "/pro/news/horizon-ablaze-2026.jpg",
    href: "https://www.tcam.museum/en/exhibition/horizon-ablaze",
  },
  {
    year: "2025",
    dates: "05 October — 20 November 2025",
    title: "Biennale Jogja 18: KAWRUH — Land of Rooted Practices",
    location: "Yogyakarta, Indonesia",
    image: "/pro/misa/misa_02.webp",
    href: "https://biennalejogja.org/2025/",
  },
  {
    year: "2025",
    dates: "17 May — 21 September 2025",
    title: "Duration of 149 Sea Miles: The Struggle of Memory Against Forgetting",
    location: "National Human Rights Museum, Taiwan",
    image: "/pro/news/duration149.webp",
    href: "https://www.nhrm.gov.tw/w/nhrmEN/Events_25090519463165280",
  },
  {
    year: "2025",
    dates: "2024.11.23 (Sat.) — 12.29 (Sun.)",
    title: "《Kalentura/Fever/Tio̍h-sua》探索熱與文化交織的全球現象系列計畫",
    location: "絕對空間, Tainan, Taiwan",
    dates: "23 November — 29 December 2024",
    image: "/pro/news/kalentura-fever-tioh-sua-2024.jpg",
    href: "https://artemperor.tw/focus/6284",
  },
  {
    year: "2024",
    dates: "11 May — 09 June 2024",
    title: "Bad Romance: Affective Body with its Misconceptions and Rumours",
    location: "Waley Art, Taipei, Taiwan",
    image: "/pro/news/badromance.webp",
    href: "https://www.facebook.com/events/419124790911287?locale=zh_TW",
  },
  {
    year: "2024",
    dates: "09 May — 07 July 2024",
    title: "Fever Dream",
    location: "UP Vargas Museum, Manila, Philippines",
    image: "/pro/news/feverdream.webp",
    href: "https://vargasmuseum.org/fever-dream/",
  },
];

const legacyPressItems = [
  {
    year: "2025",
    type: "Review",
    title: "當代藝術的「集體」，是在地共生或品牌行銷？",
    source: "The Reporter",
    href: "https://www.twreporter.org/a/photo-2025-jogja-biennale-kawruh-smooth-or-rough-collective",
  },
  {
    year: "2025",
    type: "Feature",
    title: "離開展牆，走向土地：在交流中生長的日惹雙年展",
    source: "Museum Island",
    href: "https://museums.moc.gov.tw/InternationalNew/Detail/e8ad2450-dae7-4b99-bea9-7d9b64c81163",
  },
  {
    year: "2025",
    type: "Focus",
    title: "【藝術二分之一：Art kak’i’iyaeh】檔案迴聲與未來拼圖：青年原住民藝術家Posak Jodian與豆宜臻的尋路創作",
    source: "ARTEMPORER",
    href: "https://artemperor.tw/focus/6914",
  },
  {
    year: "2024",
    type: "Video",
    title: "Video documentation",
    source: "YouTube",
    href: "https://youtu.be/vYsl60HToiw?si=OCtog4Y-pLYLFbwO",
  },
  {
    year: "2023",
    type: "Interview",
    title: "2023 Pulima藝術獎得主專訪：她們如何尋找原民性的新敘事認同？",
    source: "ARTouch",
    href: "https://artouch.com/art-views/content-114819.html",
  },
  {
    year: "2023",
    type: "Interview",
    title: "Radiw Misafafahiyan and Radiw No Orip",
    source: "CLABO Experimental Waves",
    image: "/pro/news/clabo.webp",
    href: "https://mag.clab.org.tw/clabo-article/radiw-misafafahiyan-and-radiw-no-orip/",
  },
  {
    year: "2021",
    type: "Award",
    title: "Pulima Art Award",
    source: "Pulima",
    href: "https://www.pulima.com.tw/websites/Pulima/xxxx_21111514310733457.aspx?fbclid=IwAR3p7OjUtI-0CeYdGoLA8VFfHQFUoueGvpBvE48y1jwelB2CkOiLz48b75g",
  },
];

const previousPressItems = [
  {
    year: "2026",
    type: "Review",
    title: "WE Are Becoming",
    source: "CLABO Experimental Waves",
    href: "https://mag.clab.org.tw/clabo-article/we-are-becoming/",
  },
  {
    year: "2025",
    type: "Review",
    title: "當代藝術的「集體」，是在地共生或品牌行銷？──2025日惹雙年展《Kawruh》現場觀察",
    source: "The Reporter",
    href: "https://www.twreporter.org/a/photo-2025-jogja-biennale-kawruh-smooth-or-rough-collective",
  },
  {
    year: "2025",
    type: "Feature",
    title: "離開展牆，走向土地：在交流中生長的日惹雙年展",
    source: "Museum Island",
    href: "https://museums.moc.gov.tw/InternationalNew/Detail/e8ad2450-dae7-4b99-bea9-7d9b64c81163",
  },
  {
    year: "2025",
    type: "Focus",
    title: "【藝術二分之一：Art kak’i’iyaeh】檔案迴聲與未來拼圖：青年原住民藝術家Posak Jodian與豆宜臻的尋路創作",
    source: "ARTEMPORER",
    href: "https://artemperor.tw/focus/6914",
  },
  {
    year: "2024",
    type: "Video",
    title: "kak’i’iyaeh：行動，煉化成藝術的光",
    source: "YouTube",
    href: "https://youtu.be/vYsl60HToiw?si=OCtog4Y-pLYLFbwO",
  },
  {
    year: "2023",
    type: "Interview",
    title: "2023Pulima藝術獎得主專訪：她們如何尋找原民性的新敘事認同？",
    source: "ARTouch",
    href: "https://artouch.com/art-views/content-114819.html",
  },
  {
    year: "2023",
    type: "Interview",
    title: "Radiw（歌謠）、Misafafahiyan（蛻變），和那些用歌說故事的人",
    source: "CLABO Experimental Waves",
    image: "/pro/news/clabo.webp",
    href: "https://mag.clab.org.tw/clabo-article/radiw-misafafahiyan-and-radiw-no-orip/",
  },
  {
    year: "2021",
    type: "Award",
    title: "用身體經驗一條河—Posak Jodian「Lakec渡河」計畫",
    source: "Pulima",
    href: "https://www.pulima.com.tw/websites/Pulima/xxxx_21111514310733457.aspx?fbclid=IwAR3p7OjUtI-0CeYdGoLA8VFfHQFUoueGvpBvE48y1jwelB2CkOiLz48b75g",
  },
];

export const pressItems = [
  {
    year: "2026",
    type: "Review",
    title: "WE Are Becoming",
    source: "CLABO Experimental Waves",
    href: "https://mag.clab.org.tw/clabo-article/we-are-becoming/",
  },
  {
    year: "2025",
    type: "Review",
    title: "Collectivity in Contemporary Art: Local Coexistence or Brand Marketing? Field Notes from the 2025 Jogja Biennale “Kawruh”",
    source: "The Reporter",
    href: "https://www.twreporter.org/a/photo-2025-jogja-biennale-kawruh-smooth-or-rough-collective",
  },
  {
    year: "2025",
    type: "Feature",
    title: "Leaving the Exhibition Wall and Moving Toward the Land: The Jogja Biennale Grown Through Exchange",
    source: "Museum Island",
    href: "https://museums.moc.gov.tw/InternationalNew/Detail/e8ad2450-dae7-4b99-bea9-7d9b64c81163",
  },
  {
    year: "2025",
    type: "Focus",
    title: "Art kak’i’iyaeh: Archival Echoes and Future Puzzles — Young Indigenous Artists Posak Jodian and Tou Yi-Chen’s Pathfinding Practices",
    source: "ARTEMPORER",
    href: "https://artemperor.tw/focus/6914",
  },
  {
    year: "2024",
    type: "Video",
    title: "kak’i’iyaeh: Action Transformed into the Light of Art",
    source: "YouTube",
    href: "https://youtu.be/vYsl60HToiw?si=OCtog4Y-pLYLFbwO",
  },
  {
    year: "2023",
    type: "Interview",
    title: "2023 Pulima Art Award Winner Interview: Searching for New Narrative Identities of Indigeneity",
    source: "ARTouch",
    href: "https://artouch.com/art-views/content-114819.html",
  },
  {
    year: "2023",
    type: "Interview",
    title: "Radiw, Misafafahiyan, and the People Who Tell Stories Through Song",
    source: "CLABO Experimental Waves",
    image: "/pro/news/clabo.webp",
    href: "https://mag.clab.org.tw/clabo-article/radiw-misafafahiyan-and-radiw-no-orip/",
  },
  {
    year: "2021",
    type: "Award",
    title: "Experiencing a River Through the Body — Posak Jodian’s Lakec River-Crossing Project",
    source: "Pulima",
    href: "https://www.pulima.com.tw/websites/Pulima/xxxx_21111514310733457.aspx?fbclid=IwAR3p7OjUtI-0CeYdGoLA8VFfHQFUoueGvpBvE48y1jwelB2CkOiLz48b75g",
  },
];

export const texts = [
  {
    year: "2022",
    title: "We — In Between Kita and Kami #Kami #Kita",
    source: "Nusantara Archive Project · Keyword Dictionary of Asian Contemporary Art",
    excerpt:
      "A collaboration unfolding cultural exchange through language, Indigenous experience and the shared Austronesian world.",
    href: "https://www.keywordsart.com/Astronesian-Atlas.php",
  },
  {
    year: "2021",
    title: "Lakec and Lakec: A Very Simple River",
    source: "No Man’s Land · Issue 50: The Portal & The Rearview Mirror",
    excerpt:
      "An account of field research moving between Taiwan and the Malay Peninsula, oral histories and lived experience.",
    image: "/pro/text/cilifenam.webp",
    href: "https://www.heath.tw/nml-article/lakec-and-lakec-a-very-simple-river/",
  },
  {
    year: "2021",
    title: "Remapping",
    source: "Pulima Link · Curated by Huang Ching-Ing",
    excerpt:
      "Artists remap nodes and paths, suturing fragmented stories into a new field of resonance.",
    image: "/pro/text/remapping.webp",
    href: "https://www.pulima.com.tw/PulimaENG/exhibition_202101.aspx",
  },
  {
    year: "2019",
    title: "Palm Trees, Helicopters, the Boulder, and the Storyteller",
    source: "Nusantara Archive Project · No Man’s Land",
    excerpt:
      "A journey through community, memory and storytelling across the Malay Peninsula.",
    image: "/pro/text/palmtrees.webp",
    href: "https://www.heath.tw/nml-article/palm-trees-helicopters-the-boulder-and-the-storyteller/",
  },
];

export const awards = [
  [
    "2023",
    "《Misafafahiyan 蛻變》獲 Pulima 藝術獎評審獎",
    "Misafafahiyan Metamorphosis received a Jury Award in the Pulima Art Award.",
  ],
  [
    "2021",
    "《Lakec 系列》獲 Pulima 藝術獎優選",
    "Lakec series received an Excellent Work Award in the Pulima Art Award.",
  ],
];

export const cvExhibitions = [
  ["2026", "《Misafafahiyan - Teman dari Jauh》，〈熱暑人－熱／暑的文化與當代藝術〉，臺中市立美術館，台中，台灣", "Misafafahiyan - Friend from Afar, “Horizon Ablaze”, Taichung Museum of Art, Taichung, Taiwan."],
  ["2026", "《在那幾乎看不見光的屋裡》，C-LAB 年度大展〈我們正成為〉，臺灣當代文化實驗場 (C-LAB)，台北，台灣", "Within the Unlit House, 2026 Annual Exhibition “WE Are Becoming”, Taiwan Contemporary Culture Lab (C-LAB), Taipei, Taiwan."],
  ["2025", "《Misafafahiyan - Teman dari Jauh》，BIENNALE JOGJA 18〈KAWRUH：紮根實踐之地〉，Toko Purnama，日惹，印尼", "Misafafahiyan - Friend from Afar, Biennale Jogja 18 “KAWRUH: Land of Rooted Practices”, Toko Purnama, Yogyakarta, Indonesia."],
  ["2025", "《山裡有隻白色的鹿》，2025綠島人權藝術季〈一四九海浬的時間：對抗遺忘〉，綠島國家人權博物館，綠島，台灣", "There is a white deer in the mountain, Green Island Biennial 2025 “Duration of 149 Sea Miles: The Struggle of Memory against Forgetting”, National Human Rights Museum, Green Island, Taiwan."],
  ["2025", "《Misafafahiyan 蛻變》〈往來/照見〉，新北市美術館，新北市，台灣", "Misafafahiyan Metamorphosis, “NTCAM Collection: Encounters in Reflection”, New Taipei City Art Museum, New Taipei City, Taiwan."],
  ["2025", "《Lakec》，〈往來/照見〉，新北市美術館，新北市，台灣", "Lakec, “NTCAM Collection: Encounters in Reflection”, New Taipei City Art Museum, New Taipei City, Taiwan."],
  ["2024", "《Lakec 系列》〈Kalentura/Fever/Tioh-sua〉，絕對空間，台南，台灣", "Lakec series, “Kalentura/Fever/Tioh-sua”, Absolute Space, Tainan, Taiwan."],
  ["2024", "《Misafafahiyan 蛻變》，〈壞戀：情動身體的誤讀與蜚語〉，水谷藝術，台北，台灣", "Misafafahiyan Metamorphosis, “Bad Romance: Affective Body with its Misconceptions and Rumours”, Waley Art, Taipei, Taiwan."],
  ["2024", "《Lakec》，〈Fever Dream〉，El Museo de Arte Contemporáneo de Panamá (MAC Panamá)，巴拿馬，巴拿馬", "Lakec, “Fever Dream”, El Museo de Arte Contemporáneo de Panamá (MAC Panamá), Provincia de Panamá, Panamá."],
  ["2024", "《Lakec》，〈Fever Dream〉，UP Vargas Museum，馬尼拉，菲律賓", "Lakec, “Fever Dream”, UP Vargas Museum, Manila, Philippines."],
  ["2023", "《Misafafahiyan 蛻變》，2023 Pulima 藝術節—酷兒主題展〈情山色海：酷兒・原民・秘密史〉，花蓮文化創意展業園區，花蓮，台灣", "Misafafahiyan Metamorphosis, 2023 Pulima Art Festival “Amorous Mountains, Erotic Seas: Queer, Indigene, and the Hidden History”, Hualien Creative and Cultural Industries Park, Hualien, Taiwan."],
  ["2023", "《Misafafahiyan 蛻變》，Jogja Fotografis Festival〈Frame〉，Gallery R.J. Katamsi ISI，日惹，印尼", "Misafafahiyan Metamorphosis, Jogja Fotografis Festival “Frame”, Galeri R. J. Katamsi, Yogyakarta, Indonesia."],
  ["2023", "《Misafafahiyan 蛻變》，〈海洋與詮釋者〉，Britto Arts Trust，孟加拉，達卡", "Misafafahiyan Metamorphosis, “The Oceans and the Interpreters”, Britto Arts Trust, Dhaka, Bangladesh."],
  ["2022", "《Misafafahiyan 蛻變》，〈海洋與詮釋者〉，本事藝術，台北，台灣", "Misafafahiyan Metamorphosis, “The Oceans and the Interpreters”, Solid Art, Taipei, Taiwan."],
  ["2022", "《Lakec: A Very Simple River》，〈另一座板塊〉，台東美術館，台灣", "Lakec: A Very Simple River, “Another Continent”, Taitung Art Museum, Taitung, Taiwan."],
  ["2021", "《Lakec: A Very Simple River》，〈海洋與詮釋者–詮釋者放映計畫：神秘之島〉，鳳甲美術館，台北，台灣", "Lakec: A Very Simple River, “The Oceans and the Interpreters’ Screening II: The Mysterious Island”, Hong-gah Museum, Taipei, Taiwan."],
  ["2020", "《Lakec: A Very Simple River》，群島資料庫計畫，〈秘密南方〉，台北市立美術館，台北，台灣", "Lakec: A Very Simple River, participated in Nusantara Archive project, “The Secret South”, Taipei Fine Arts Museum, Taipei, Taiwan."],
  ["2019", "《Palm Trees, Helicopters, the Boulder, and the Storyteller》收錄於群島資料庫計畫，刊登於 No Man’s Land 線上平台", "Palm Trees, Helicopters, the Boulder, and the Storyteller included in Nusantara Archive, published on the No Man’s Land online platform."],
  ["2019", "《Bitter Sweet》，打開-當代藝術工作站計畫，2019亞洲藝術雙年展〈來自山與海的異人〉，台中，台灣", "Bitter Sweet, participated in Open Contemporary Art Center (OCAC)’s project “Deposits of the Island”, 2019 Asian Art Biennial: The Strangers from beyond the Mountain and the Sea, Taiwan Museum of Fine Arts, Taichung, Taiwan."],
  ["2018", "《Lakec》，A+ WORKS of ART〈A+ Online Festival of Video Art〉，吉隆坡，馬來西亞", "Lakec, “A+ Online Festival of Video Art”, Kuala Lumpur, Malaysia."],
  ["2018", "《Lakec》，〈邊境旅行 PETAMU Project〉，打開-當代藝術工作站，台北，台灣", "Lakec, “PETAMU Project”, Open Contemporary Art Center (OCAC), Taipei, Taiwan."],
];
